### ISSUE TITLE
Поддержка Ubuntu 22

### ISSUE THREAD

**Issue by synalice** [keygenqt/aurora-toolbox#12]
Очень много разработчиков ((Московский офис)) всё ещё используют Ubuntu 22.04 LTS (Jammy Jellyfish), так как она является Long Term Support ещё аж до 2027 года.

Использовать в такой ситуации bleeding edge технологии _очень_ недальновидно и отсекает очень много людей.

**Comment by keygenqt** [comment]
Поддержки 22.04 не будет.
