### ISSUE TITLE
Не устанавливается flutter 

### ISSUE THREAD

**Issue by zheleznyakov** [keygenqt/aurora-toolbox#3]
В последней версии перестал устанавливаться flutter
![Снимок экрана от 2024-10-26 12-41-13](https://github.com/user-attachments/assets/0a6370db-945f-483b-96ef-776de23b5bba)
Приложение aurora-toolbox пишет something went wrong

**Comment by keygenqt** [comment]
Хм, чекнул на последней. Нужно больше подробностей.
![image](https://github.com/user-attachments/assets/69501de3-d6da-4b3a-a735-4b827927eb73)

**Comment by zheleznyakov** [comment]
Разобрался. Ошибка вываливается, если не установлен git. У меня на виртуалке не был установлен.

**Comment by keygenqt** [comment]
[bug] Add check dependency git.
https://github.com/keygenqt/aurora-cli/commit/3e74d7cfc4e2231a9df53efd62893803a87d2b72
