### ISSUE TITLE
Улучшить ярлык + алиас на бинарник

### ISSUE THREAD

**Issue by Sash0k** [keygenqt/aurora-toolbox#5]
Привет, сейчас в ярлыке полный путь до бинарника `Exec=/usr/local/bin/com.keygenqt.aurora-toolbox`
Предлагаю пару улучшений: 

- сделать алиас **aurora-toolbox** вместо полного имени **com.keygenqt.aurora-toolbox**. При установке из deb/rpm можно просто делать симлинк, без изменений в проекте
- прописать `Exec=aurora-toolbox`, без полного пути (пусть система ищет его в PATH)

**Comment by keygenqt** [comment]
Добавил, спасибо за идею.
https://github.com/keygenqt/aurora-toolbox/commit/910fd71c0af93427cfab63b9a8215a343412cf6b
