### ISSUE TITLE
Определение светлой/темной темы может не работать в средах, отличных от GNOME.

### ISSUE THREAD

**Issue by Sash0k** [keygenqt/aurora-toolbox#9]
**Связан ли ваш запрос на функцию с проблемой? Опишите.**
* При запуске тулбокса в Альт XFCE есть проблема с сервисом d-bus (даже при установке всех нужных зависимостей):
`GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop`
* Это не касается конкретно Альтлинукса, а связано со сломанным экспортом интерфейса `org.freedesktop.portal.Settings` при разработке [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal/pull/1358)
* Вот статья, описывающая эту же проблему в ubuntu: https://tommie.github.io/a/2024/08/xfce-gnome-dark-mode
* MATE/Cinnamon/LXDE/etc не проверял, предположительно будет также.

**Опишите решение, которое вы хотели бы**
Сейчас **DBusProxy.js** пытается считать темную-светлую тему из d-bus. Возможно стоит добавить проверку, и если интерфейса d-bus нет, использовать тему по умолчанию (например, светлую)

**Опишите альтернативы, которые вы рассматривали**
Чтобы тулбокс заработал, можно поставить`gnome-extensions-app` (сейчас он прописан зависимостью, и это очень избыточно) или `gnome-shell`, которые тянут GNOME - там проблемы нет

Если правильно понимаю, проблема будет решена после релиза **xdg-desktop-portal 1.20** и затаскивания его в дистрибутивы

**Comment by Sash0k** [comment]
* в Альте баг воспроизводится только, если устанавливать пакеты в особом порядке, завёл им [тикет](https://bugzilla.altlinux.org/52041)
* в других дистрибутивах проблема в XFCE будет на версиях, описанных по ссылкам в комментарии выше (у Альта версии зависимостей чуть выше, и похоже проблема частично устранена)

считаю что приоритет у проблемы минорный, можно даже закрыть 🪲

**Comment by keygenqt** [comment]
Добавил "ручную" установку темы.
https://github.com/keygenqt/aurora-toolbox/commit/a9d4520e6eea198d332a00dcce60b5288601d324

![image](https://github.com/user-attachments/assets/cb4ad84f-bf95-43fa-9426-434246f8766f)
